<a href="https://colab.research.google.com/github/DanielLaBanda/DanielLaBanda/blob/main/A01285898_M1_Actividad_5_Programaci%C3%B3n_en_Python_Librer%C3%ADas_Numpy_Matplotlib_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <h2>Ejercicio 1 (Numpy)</h2>
  <ol>
    <li>Crear un vector “x” con 10 ceros y mostrarlo.</li>
    <li>Modificar el quinto elemento del vector x para que su valor sea 3.</li>
    <li>Crear un vector “y” con valores del 1 al 20, de 1 en 1. Utiliza la función arange.</li>
    <li>Crear un vector “z” con valores del 1 al 20, de 2 en 2.</li>
    <li>Crear una matriz w de 3x2, con valores iniciales en 0.</li>
    <li>Modificar el elemento en la posición 2,2 de la matriz w para que su valor sea 5.</li>
    <li>Crear un vector de 5 elementos, con valores aleatorios enteros entre 1 y 10.</li>
    <li>Crear el arreglo x1 de la lista [1,2,3].</li>
    <li>Sumar 10 a cada elemento del vector.</li>
  </ol>
</body>
</html>


In [ ]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
x[4] = 3
x

array([0., 0., 0., 0., 3., 0., 0., 0., 0., 0.])

In [ ]:
y = np.arange(1, 21)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
z = np.arange(1, 20, 2)
z

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
w = np.zeros([3, 2])
w

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
w[1, 1] = 5
w

array([[0., 0.],
       [0., 5.],
       [0., 0.]])

In [ ]:
random = np.random.randint(1, 11, 5)
random

array([ 4,  5, 10,  5,  5])

In [ ]:
lista = [1, 2, 3]
x1 = np.array(lista)
x1

array([1, 2, 3])

In [ ]:
x1 += 10
x1

array([11, 12, 13])

<!DOCTYPE html>
<html>
<head>
  <title>Ejercicio Titanic (Pandas)</title>
</head>
<body>
  <h2>Ejercicio Titanic (Pandas)</h2>
  <p>El archivo <strong>titanic.csv</strong> contiene información sobre los pasajeros del Titanic. Escribir un programa con los siguientes requisitos:</p>
  <ol>
    <li>Generar un DataFrame con los datos del archivo.</li>
    <li>Mostrar por pantalla las dimensiones del DataFrame, el número de datos que contiene, los nombres de sus columnas y filas, los tipos de datos de las columnas, las 10 primeras filas y las 10 últimas filas.</li>
    <li>Mostrar por pantalla los datos del pasajero con identificador 148.</li>
    <li>Mostrar por pantalla las filas pares del DataFrame.</li>
    <li>Mostrar por pantalla los nombres de las personas que iban en primera clase ordenadas alfabéticamente.</li>
    <li>Mostrar por pantalla el porcentaje de personas que sobrevivieron y murieron.</li>
    <li>Mostrar por pantalla el porcentaje de personas que sobrevivieron en cada clase.</li>
    <li>Eliminar del DataFrame los pasajeros con edad desconocida.</li>
    <li>Mostrar por pantalla la edad media de las mujeres que viajaban en cada clase.</li>
    <li>Añadir una nueva columna booleana para ver si el pasajero era menor de edad o no.</li>
    <li>Mostrar por pantalla el porcentaje de menores y mayores de edad que sobrevivieron en cada clase.</li>
  </ol>
</body>
</html>


In [58]:
dataset = pd.read_csv('/content/titanic-1.csv')
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [69]:
print('Dimensiones:', dataset.shape)
print('Número de elementos:', dataset.size)
print('Nombres de columnas:', dataset.columns)
print('Nombres de filas:', dataset.index)
print('Tipos de datos:\n', dataset.dtypes)

Dimensiones: (891, 12)
Número de elementos: 10692
Nombres de columnas: Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
Nombres de filas: RangeIndex(start=0, stop=891, step=1)
Tipos de datos:
 PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [60]:
dataset.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [61]:
dataset.tail(10)

PassengerId  Survived  Pclass                                      Name  \
881          882         0       3                        Markun, Mr. Johann   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
883          884         0       2             Banfield, Mr. Frederick James   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
881    male  33.0      0      0            349257   7.8958   NaN        S  
882  female  22.0      0      0              7552  10.5167   NaN        S  
883    male  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
887  female  19.0      0      0            112053  30.0000   B42        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
889    male  26.0      0      0            111369  30.0000  C148        C  
890    male  32.0      0      0            370376   7.7500   NaN        Q

In [62]:
dataset.iloc[147, :]

PassengerId                                 148
Survived                                      0
Pclass                                        3
Name           Ford, Miss. Robina Maggie "Ruby"
Sex                                      female
Age                                         9.0
SibSp                                         2
Parch                                         2
Ticket                               W./C. 6608
Fare                                     34.375
Cabin                                       NaN
Embarked                                      S
Name: 147, dtype: object

In [63]:
dataset.iloc[::2, :]

PassengerId  Survived  Pclass  \
0              1         0       3   
2              3         1       3   
4              5         0       3   
6              7         0       1   
8              9         1       3   
..           ...       ...     ...   
882          883         0       3   
884          885         0       3   
886          887         0       2   
888          889         0       3   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
4                             Allen, Mr. William Henry    male  35.0      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
..                                                 ...     ...   ...    ...   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
884                             Sutehall, Mr. Henry Jr    male  25.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
2        0  STON/O2. 3101282   7.9250   NaN        S  
4        0            373450   8.0500   NaN        S  
6        0             17463  51.8625   E46        S  
8        2            347742  11.1333   NaN        S  
..     ...               ...      ...   ...      ...  
882      0              7552  10.5167   NaN        S  
884      0   SOTON/OQ 392076   7.0500   NaN        S  
886      0            211536  13.0000   NaN        S  
888      2        W./C. 6607  23.4500   NaN        S  
890      0            370376   7.7500   NaN        Q  

[446 rows x 12 columns]

In [64]:
dataset[dataset['Pclass'] == 1].sort_values(by=['Name'])

PassengerId  Survived  Pclass  \
730          731         1       1   
305          306         1       1   
297          298         0       1   
498          499         0       1   
460          461         1       1   
..           ...       ...     ...   
155          156         0       1   
351          352         0       1   
55            56         1       1   
555          556         0       1   
325          326         1       1   

                                                Name     Sex    Age  SibSp  \
730                    Allen, Miss. Elisabeth Walton  female  29.00      0   
305                   Allison, Master. Hudson Trevor    male   0.92      1   
297                     Allison, Miss. Helen Loraine  female   2.00      1   
498  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00      1   
460                              Anderson, Mr. Harry    male  48.00      0   
..                                               ...     ...    ...    ...   
155                      Williams, Mr. Charles Duane    male  51.00      0   
351           Williams-Lambert, Mr. Fletcher Fellows    male    NaN      0   
55                                 Woolner, Mr. Hugh    male    NaN      0   
555                               Wright, Mr. George    male  62.00      0   
325                         Young, Miss. Marie Grice  female  36.00      0   

     Parch    Ticket      Fare    Cabin Embarked  
730      0     24160  211.3375       B5        S  
305      2    113781  151.5500  C22 C26        S  
297      2    113781  151.5500  C22 C26        S  
498      2    113781  151.5500  C22 C26        S  
460      0     19952   26.5500      E12        S  
..     ...       ...       ...      ...      ...  
155      1  PC 17597   61.3792      NaN        C  
351      0    113510   35.0000     C128        S  
55       0     19947   35.5000      C52        S  
555      0    113807   26.5500      NaN        S  
325      0  PC 17760  135.6333      C32        C  

[216 rows x 12 columns]

In [71]:
total = dataset['Survived'].count()
died = (dataset['Survived'].value_counts()[0]) / total
survived = (dataset['Survived'].value_counts()[1]) / total
print(f'Porcentaje de personas que murieron: {died*100:.2f}%')
print(f'Porcentaje de personas que sobrevivieron: {survived*100:.2f}%')

Porcentaje de personas que murieron: 61.62%
Porcentaje de personas que sobrevivieron: 38.38%
