<a href="https://colab.research.google.com/github/DanielLaBanda/DanielLaBanda/blob/main/A01285898_M1_Actividad_5_Programaci%C3%B3n_en_Python_Librer%C3%ADas_Numpy_Matplotlib_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
  <h2>Ejercicio 1 (Numpy)</h2>
  <ol>
    <li>Crear un vector “x” con 10 ceros y mostrarlo.</li>
    <li>Modificar el quinto elemento del vector x para que su valor sea 3.</li>
    <li>Crear un vector “y” con valores del 1 al 20, de 1 en 1. Utiliza la función arange.</li>
    <li>Crear un vector “z” con valores del 1 al 20, de 2 en 2.</li>
    <li>Crear una matriz w de 3x2, con valores iniciales en 0.</li>
    <li>Modificar el elemento en la posición 2,2 de la matriz w para que su valor sea 5.</li>
    <li>Crear un vector de 5 elementos, con valores aleatorios enteros entre 1 y 10.</li>
    <li>Crear el arreglo x1 de la lista [1,2,3].</li>
    <li>Sumar 10 a cada elemento del vector.</li>
  </ol>
</body>
</html>


In [2]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
x[4] = 3
x

array([0., 0., 0., 0., 3., 0., 0., 0., 0., 0.])

In [4]:
y = np.arange(1, 21)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [5]:
z = np.arange(1, 20, 2)
z

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [6]:
w = np.zeros([3, 2])
w

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
w[1, 1] = 5
w

array([[0., 0.],
       [0., 5.],
       [0., 0.]])

In [8]:
random = np.random.randint(1, 11, 5)
random

array([ 4,  5, 10,  5,  5])

In [9]:
lista = [1, 2, 3]
x1 = np.array(lista)
x1

array([1, 2, 3])

In [10]:
x1 += 10
x1

array([11, 12, 13])

<!DOCTYPE html>
<html>
<head>
  <title>Ejercicio Titanic (Pandas)</title>
</head>
<body>
  <h2>Ejercicio Titanic (Pandas)</h2>
  <p>El archivo <strong>titanic.csv</strong> contiene información sobre los pasajeros del Titanic. Escribir un programa con los siguientes requisitos:</p>
  <ol>
    <li>Generar un DataFrame con los datos del archivo.</li>
    <li>Mostrar por pantalla las dimensiones del DataFrame, el número de datos que contiene, los nombres de sus columnas y filas, los tipos de datos de las columnas, las 10 primeras filas y las 10 últimas filas.</li>
    <li>Mostrar por pantalla los datos del pasajero con identificador 148.</li>
    <li>Mostrar por pantalla las filas pares del DataFrame.</li>
    <li>Mostrar por pantalla los nombres de las personas que iban en primera clase ordenadas alfabéticamente.</li>
    <li>Mostrar por pantalla el porcentaje de personas que sobrevivieron y murieron.</li>
    <li>Mostrar por pantalla el porcentaje de personas que sobrevivieron en cada clase.</li>
    <li>Eliminar del DataFrame los pasajeros con edad desconocida.</li>
    <li>Mostrar por pantalla la edad media de las mujeres que viajaban en cada clase.</li>
    <li>Añadir una nueva columna booleana para ver si el pasajero era menor de edad o no.</li>
    <li>Mostrar por pantalla el porcentaje de menores y mayores de edad que sobrevivieron en cada clase.</li>
  </ol>
</body>
</html>


In [12]:
dataset = pd.read_csv('/content/titanic-1.csv')
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S